Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Rails/HasAndBelongsToMany:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30
  Exclude:
    - app/controllers/users/event_controller.rb

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Max: 60

Metrics/ClassLength:
  Max: 120

AllCops:
  Exclude:
    - db/**/*
    - bin/**/*
    - vendor/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - assets/**/*
    - lib/tasks/adhoc/*
    - config/**/*
    - coverage/**/*
    - node_modules/**/*
    - app/inputs/image_preview_input.rb

Metrics/CyclomaticComplexity:
  Max: 10
